Repository palantir/tritium, pull requests merged in 2019-12, with the labels that each got.

#519 Deprecate SharedTaggedMetricRegistries#getSingleton
  changelog/@unreleased/pr-519.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistries.java
Labels: merge when ready

#538 Upgrade gradle-baseline and error-prone
  build.gradle
  changelog/@unreleased/pr-538.v2.yml
  tritium-core/src/main/java/com/palantir/tritium/event/InstrumentationFilters.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentationAdvice.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/SafepointMetrics.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/ReflectiveTracer.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/RemotingCompatibleTracingInvocationEventHandler.java
  versions.lock
  versions.props
Labels: merge when ready

#501 Register tagged gauge with replacement
  changelog/@unreleased/pr-501.v2.yml
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStats.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/AbstractTaggedMetricRegistry.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/TaggedMetricRegistry.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/TaggedMetricRegistryTest.java
Labels: merge when ready

#547 Deduplicate interfaces for byte-buddy instrumentation
  changelog/@unreleased/pr-547.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/InstrumentationCreationBenchmark.java
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/Stubs.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentation.java
  tritium-proxy/src/main/java/com/palantir/tritium/proxy/Proxies.java
  tritium-proxy/src/test/java/com/palantir/tritium/proxy/ProxiesTest.java
Labels: merge when ready

#551 Fix class initialization race
  changelog/@unreleased/pr-551.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/AbstractTaggedMetricRegistry.java
Labels: autorelease, merge when ready

#550 Benchmarks comparing instrumentation performance in non-standard cases
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ManyArguments.java
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
Labels: merge when ready, no changelog

#553 Downgrade error_prone_annotations 2.3.4 -> 2.3.3
  changelog/@unreleased/pr-553.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#555 RealMetricName provides a toString implementation
  changelog/@unreleased/pr-555.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/RealMetricName.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/MetricNameTest.java
Labels: merge when ready
