Repository palantir/tritium, pull requests merged in 2019-08, with the labels that each got.

#200 Add com.palantir.baseline-exact-dependencies check
  build.gradle
  tritium-caffeine/build.gradle
  tritium-core/build.gradle
  tritium-lib/build.gradle
  tritium-lib/src/test/java/com/palantir/tritium/event/log/LoggingInstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-metrics-jvm/build.gradle
  tritium-metrics/build.gradle
  tritium-registry/build.gradle
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistriesTest.java
  tritium-slf4j/build.gradle
  tritium-test/build.gradle
  tritium-tracing/build.gradle
Labels: merge when ready, no changelog, update me

#338 Upgrade to null-away 0.7.5
  versions.props
Labels: merge when ready, no changelog

#309 Add metric for JVM process cpu load
  changelog/@unreleased/pr-309.v2.yml
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/OperatingSystemMetrics.java
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
Labels: merge when ready

#353 Migrate to JUnit 5
  build.gradle
  changelog/@unreleased/pr-353.v2.yml
  tritium-caffeine/build.gradle
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheMetricsTest.java
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheTaggedMetricsTest.java
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineStatsTest.java
  tritium-core/build.gradle
  tritium-core/src/test/java/com/palantir/tritium/event/AbstractInvocationEventHandlerTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/CompositeInvocationEventHandlerTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/DefaultInvocationContextTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/InstrumentationFiltersTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/InstrumentationPropertiesTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/NoOpInvocationEventHandlerTest.java
  tritium-lib/build.gradle
  tritium-lib/src/test/java/com/palantir/tritium/JitCompilationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/TritiumTest.java
  tritium-lib/src/test/java/com/palantir/tritium/event/log/LoggingInstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
  tritium-metrics-jvm/build.gradle
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
  tritium-metrics/build.gradle
  tritium-metrics/src/test/java/com/palantir/tritium/annotations/AnnotationHelperTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/event/metrics/MetricsBooleanSupplierTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/event/metrics/MetricsInvocationEventHandlerTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/event/metrics/TaggedMetricsServiceInvocationEventHandlerTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/CacheMetricSetTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InstrumentedSslContextTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InternalCacheMetricsTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistriesTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistryWithReservoirsTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/TaggedMetricsExecutorServiceTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/TaggedMetricsScheduledExecutorServiceTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/test/TestTaggedMetricRegistries.java
  tritium-proxy/build.gradle
  tritium-proxy/src/test/java/com/palantir/tritium/proxy/ProxiesTest.java
  tritium-registry/build.gradle
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/MetricNameTest.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistriesTest.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/TaggedMetricRegistryTest.java
  tritium-registry/src/test/java/com/palantir/tritium/registry/test/TestTaggedMetricRegistries.java
  tritium-slf4j/build.gradle
  tritium-slf4j/src/test/java/com/palantir/tritium/event/log/LoggingInvocationEventHandlerTest.java
  tritium-test/build.gradle
  tritium-tracing/build.gradle
  tritium-tracing/src/test/java/com/palantir/tritium/tracing/JavaTracingTracerTest.java
  tritium-tracing/src/test/java/com/palantir/tritium/tracing/ReflectiveTracerTest.java
  tritium-tracing/src/test/java/com/palantir/tritium/tracing/TracingInvocationEventHandlerTest.java
  versions.lock
  versions.props
Labels: merge when ready

#354 Treat warnings as compile errors
  build.gradle
  changelog/@unreleased/pr-354.v2.yml
Labels: merge when ready

#355 Unset `errorProneApply=true` in gradle.properties to enable validation
  build.gradle
  gradle.properties
  tritium-jmh/build.gradle
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistriesTest.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/TaggedMetricRegistryTest.java
Labels: merge when ready, no changelog

#357 Optimize TracingInvocationEventHandler for nested use
  changelog/@unreleased/pr-357.v2.yml
  changelog/@unreleased/pr-358.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
  tritium-lib/src/test/java/com/palantir/tritium/TritiumTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/event/metrics/TaggedMetricsServiceInvocationEventHandler.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/TracingInvocationEventHandler.java
Labels: merge when ready

#359 Flatten the Tritium proxy to avoid excessive stack frames
  changelog/@unreleased/pr-359.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/BlackholeInvocationEventHandler.java
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
Labels: merge when ready

#363 newline in BlackholeInvocationEventHandler
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/BlackholeInvocationEventHandler.java
Labels: merge when ready, no changelog

#364 Test cases for corner case polymorphic instrumentation
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
Labels: merge when ready, no changelog

#367 Benchmark default Tritium.instrument configurations
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
Labels: merge when ready, no changelog

#368 Test tritium instrumentation stack depth
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
Labels: merge when ready, no changelog
