Repository palantir/tritium, pull requests merged in 2019-09, with the labels that each got.

#375 InstrumentationTest.executeManyTimes prints correct iterations
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
Labels: merge when ready, no changelog

#337 Check unused dependencies
  build.gradle
  changelog/@unreleased/pr-337.v2.yml
  tritium-caffeine/build.gradle
  tritium-jmh/build.gradle
  tritium-lib/build.gradle
  tritium-metrics-jvm/build.gradle
  tritium-metrics/build.gradle
  tritium-registry/build.gradle
  tritium-slf4j/build.gradle
  tritium-test/build.gradle
  tritium-tracing/build.gradle
Labels: merge when ready, update me

#379 CompositeInvocationEventHandler completes delegates when disabled in flight
  changelog/@unreleased/pr-379.v2.yml
  tritium-core/src/main/java/com/palantir/tritium/event/CompositeInvocationEventHandler.java
  tritium-core/src/test/java/com/palantir/tritium/event/CompositeInvocationEventHandlerTest.java
Labels: merge when ready

#389 Use Byte Buddy for Instrumentation by default
  changelog/@unreleased/pr-389.v2.yml
  tritium-core/src/main/java/com/palantir/tritium/event/InstrumentationProperties.java
  tritium-core/src/test/java/com/palantir/tritium/event/InstrumentationPropertiesTest.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/Instrumentation.java
Labels: merge when ready

#407 Use simple string concatenation over MetricRegistry.name
  changelog/@unreleased/pr-407.v2.yml
  tritium-lib/src/main/java/com/palantir/tritium/proxy/Instrumentation.java
  tritium-metrics/src/main/java/com/palantir/tritium/event/metrics/MetricsInvocationEventHandler.java
Labels: merge when ready

#418 Mark unused public method arguments
  tritium-core/src/main/java/com/palantir/tritium/event/InstrumentationFilters.java
  tritium-core/src/main/java/com/palantir/tritium/event/NoOpInvocationEventHandler.java
  tritium-core/src/test/java/com/palantir/tritium/event/CompositeInvocationEventHandlerTest.java
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
  tritium-lib/src/test/java/com/palantir/tritium/JitCompilationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/event/metrics/MetricsInvocationEventHandler.java
  tritium-metrics/src/main/java/com/palantir/tritium/event/metrics/TaggedMetricsServiceInvocationEventHandler.java
  tritium-slf4j/src/main/java/com/palantir/tritium/event/log/LoggingInvocationEventHandler.java
  tritium-test/src/main/java/com/palantir/tritium/test/TestImplementation.java
  tritium-test/src/main/java/com/palantir/tritium/test/event/ThrowingInvocationEventHandler.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/RemotingCompatibleTracingInvocationEventHandler.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/TracingInvocationEventHandler.java
  tritium-tracing/src/test/java/com/palantir/tritium/tracing/ReflectiveTracerTest.java
Labels: merge when ready

#430 Nested metric registries don't cause a sortedmap creation
  .baseline/checkstyle/checkstyle.xml
  .gitignore
  build.gradle
  changelog/@unreleased/pr-430.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/NestedMetricsBenchmark.java
  tritium-registry/build.gradle
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/AbstractTaggedMetricRegistry.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/DropwizardTaggedMetricSet.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ExtraEntrySortedMap.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/MetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/PrehashedSortedMap.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/RealMetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/TaggedMetricSet.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/ExtraEntrySortedMapTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready
