Repository palantir/tritium, pull requests merged in 2019-11, with the labels that each got.

#490 Update InvocationEventProxy for readability
  tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
Labels: merge when ready, no changelog

#502 Migrate several metrics to metric-schema
  build.gradle
  changelog/@unreleased/pr-502.v2.yml
  tritium-metrics-jvm/build.gradle
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/Jdk9CompatibleFileDescriptorRatioGauge.java
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/OperatingSystemMetrics.java
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/SafepointMetrics.java
  tritium-metrics-jvm/src/main/metrics/metrics.yml
  tritium-metrics/build.gradle
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/GarbageCollectorMetrics.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslContext.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslServerSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MemoryPoolMetrics.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/TaggedMetricsExecutorService.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/TaggedMetricsScheduledExecutorService.java
  tritium-metrics/src/main/metrics/metrics.yml
Labels: autorelease, merge when ready

#507 Fix ByteBuddyInstrumentationAdvice logger class name
  changelog/@unreleased/pr-507.v2.yml
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentationAdvice.java
Labels: merge when ready

#510 Tritium instrumentation handles null InvocationContexts
  changelog/@unreleased/pr-508.v2.yml
  changelog/@unreleased/pr-510-2.v2.yml
  changelog/@unreleased/pr-510.v2.yml
  tritium-api/src/main/java/com/palantir/tritium/event/InvocationEventHandler.java
  tritium-core/src/main/java/com/palantir/tritium/event/CompositeInvocationEventHandler.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentation.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentationAdvice.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
Labels: autorelease, merge when ready

#512 Migrate `jvm.attribute` metrics to metric-schema
  changelog/@unreleased/pr-512.v2.yml
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
  tritium-metrics-jvm/src/main/metrics/metrics.yml
Labels: autorelease, merge when ready

#515 Remove block with "known" misspelled "knownn"
  tritium-metrics/src/main/metrics/metrics.yml
Labels: merge when ready, no changelog

#516 jvm.attribute.uptime tags includes jvm vendor and version info
  changelog/@unreleased/pr-516.v2.yml
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
  tritium-metrics-jvm/src/main/metrics/metrics.yml
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
Labels: autorelease, merge when ready
