Repository palantir/tritium, pull requests merged in 2020-05, with the labels that each got.

#713 Fix typos in TLS metric documentation
  tritium-metrics/src/main/metrics/metrics.yml
Labels: merge when ready, no changelog

#712 Report metrics describing the finalizer queue size
  changelog/@unreleased/pr-712.v2.yml
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/GarbageCollectorMetrics.java
  tritium-metrics/src/main/metrics/metrics.yml
Labels: autorelease, merge when ready

#723 Baseline no longer provides a SwitchStatementDefaultCase error-prone check
  build.gradle
Labels: merge when ready

#715 Deprecated non-tagged caffeine cache metrics
  changelog/@unreleased/pr-715.v2.yml
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStats.java
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistriesTest.java
Labels: autorelease, merge when ready
