Repository palantir/tritium, pull requests merged in 2020-03, with the labels that each got.

#651 Use jcenter repository for gradle plugins and dependencies.
  build.gradle
  changelog/@unreleased/pr-651.v2.yml
Labels: merge when ready

#655 Upgrade jmh infrastructure
  changelog/@unreleased/pr-655.v2.yml
  tritium-jmh/build.gradle
  versions.props
Labels: merge when ready

#656 Reduce jqwik dependency to jqwik-api
  changelog/@unreleased/pr-656.v2.yml
  tritium-registry/build.gradle
  versions.lock
  versions.props
Labels: merge when ready

#658 Upgrade gradle-baseline to 3.7.4
  .baseline/checkstyle/checkstyle.xml
  build.gradle
  tritium-caffeine/build.gradle
  tritium-core/build.gradle
  tritium-jmh/build.gradle
  tritium-lib/build.gradle
  tritium-metrics-jvm/build.gradle
  tritium-metrics/build.gradle
  tritium-proxy/build.gradle
  tritium-registry/build.gradle
  tritium-slf4j/build.gradle
  tritium-test/build.gradle
  tritium-tracing/build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#671 Instrumented executors use final classes
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/TaggedMetricsExecutorService.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/TaggedMetricsScheduledExecutorService.java
Labels: merge when ready, no changelog

#672 Implement equals and hashcode on instrumented TLS components
  changelog/@unreleased/pr-672.v2.yml
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslContext.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslServerSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslSocketFactory.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InstrumentedSslContextTest.java
Labels: autorelease, merge when ready

#673 Document InstrumentedSslEngine design and behavior
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
Labels: merge when ready, no changelog
