Repository palantir/tritium, pull requests merged in 2020-10, with the labels that each got.

#865 Update the LockFreeExponentiallyDecayingReservoir based on upstream feedback
  changelog/@unreleased/pr-865.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/LockFreeExponentiallyDecayingReservoir.java
Labels: autorelease, merge when ready

#867 Update LockFreeExponentiallyDecayingReservoir based on upstream feedback
  changelog/@unreleased/pr-867.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/LockFreeExponentiallyDecayingReservoir.java
Labels: merge when ready

#866 Simplify TracingInvocationEventHandler using `hasUnobservableTrace`
  changelog/@unreleased/pr-866.v2.yml
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/TracingInvocationEventHandler.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#862 Enable JDK 11 and 15 test runs
  .circleci/config.yml
  .circleci/template.sh
Labels: merge when ready, no changelog

#869 Fix LockFreeExponentiallyDecayingReservoir potential race
  changelog/@unreleased/pr-869.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/LockFreeExponentiallyDecayingReservoir.java
Labels: autorelease, merge when ready
