Repository palantir/tritium, pull requests merged in 2020-09, with the labels that each got.

#842 Use JMH 1.25.2
  versions.props
Labels: merge when ready, no changelog, update me

#851 Use error-prone 2.4.0
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#852 Dependabot uses no changelog label
  .github/dependabot.yml
Labels: merge when ready, no changelog

#860 Implement a lock-free exponential decaying reservoir
  changelog/@unreleased/pr-860.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ReservoirBenchmarks.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/DefaultTaggedMetricRegistry.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/LockFreeExponentiallyDecayingReservoir.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/LockFreeExponentiallyDecayingReservoirTest.java
Labels: merge when ready
