Repository palantir/tritium, pull requests merged in 2020-07, with the labels that each got.

#780 Suppress too many arguments for many arguments performance test
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ManyArguments.java
Labels: merge when ready

#781 Upgrade CircleCI build to JDK 8u252
  .circleci/config.yml
  changelog/@unreleased/pr-781.v2.yml
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
Labels: merge when ready

#785 Setup dependabot
  .github/dependabot.yml
Labels: merge when ready, no changelog

#788 Remove Checkstyle guava version override
  build.gradle
  changelog/@unreleased/pr-788.v2.yml
Labels: merge when ready

#790 Add `instrument.tls.socket` property to disable handshake metrics using sockets
  changelog/@unreleased/pr-790.v2.yml
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslServerSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslSocketFactory.java
Labels: autorelease, merge when ready

#791 Do not mock Guava caches in tests
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/CacheMetricSetTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistriesTest.java
Labels: merge when ready

#795 Fix build config to run junit tests
  build.gradle
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InstrumentedSslContextTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InternalCacheMetricsTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/TaggedMetricsExecutorServiceTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/TaggedMetricsScheduledExecutorServiceTest.java
  tritium-tracing/src/test/java/com/palantir/tritium/tracing/TracingInvocationEventHandlerTest.java
Labels: merge when ready, no changelog

#793 fix #794 Socket handshake metrics are not recorded by default
  changelog/@unreleased/pr-792.v2.yml
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/HandshakeInstrumentation.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslServerSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslSocketFactory.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InstrumentedSslContextTest.java
Labels: autorelease, merge when ready
