Repository palantir/tritium, pull requests merged in 2021-07, with the labels that each got.

#1135 Share single DefaultTaggedMetricRegistry backed by LockFreeExponentiallyDecayingReservoir
  changelog/@unreleased/pr-1135.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/DefaultTaggedMetricRegistry.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistries.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/SharedTaggedMetricRegistriesTest.java
Labels: autorelease, merge when ready

#1142 Report the number of loaded classes as an isolated metric
  changelog/@unreleased/pr-1142.v2.yml
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
  tritium-metrics-jvm/src/main/metrics/metrics.yml
Labels: autorelease, merge when ready

#1143 tritium-processor outputs are formatted with PJF
  changelog/@unreleased/pr-1143.v2.yml
  tritium-processor/build.gradle
  tritium-processor/src/main/java/com/palantir/tritium/processor/TritiumAnnotationProcessor.java
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedBindsParameter.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDelegateToCallable.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDelegateToRunnable.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDeprecatedInterface.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDeprecatedMethod.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedHasDefaultMethod.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedHasToString.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedOverlappingNames.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedOverloaded.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedParameterized.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedSimple.java.generated
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1163 EqualsMissingNullable Add @Nullable to equals
  tritium-metrics/src/main/java/com/palantir/tritium/event/metrics/annotations/AnnotationHelper.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslContext.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslServerSocketFactory.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslSocketFactory.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ExtraEntrySortedMap.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/MetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/RealMetricName.java
Labels: autorelease, merge when ready, no changelog

#1170 Enforce 'PreferSafeLogger'
  build.gradle
Labels: merge when ready, no changelog
