Repository palantir/tritium, pull requests merged in 2021-02, with the labels that each got.

#993 Apply ConsistentLoggerName
  tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/RemotingCompatibleTracingInvocationEventHandler.java
Labels: merge when ready, no changelog

#996 Use Caffeine CacheStats.of for testing
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineStatsTest.java
Labels: merge when ready, no changelog

#999 Delegate to the jvm-diagnostics library for safepoint time
  changelog/@unreleased/pr-999.v2.yml
  tritium-metrics-jvm/build.gradle
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/SafepointMetrics.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#997 LoggingInvocationEventHandler precomputes level information
  changelog/@unreleased/pr-997.v2.yml
  tritium-lib/src/test/java/com/palantir/tritium/event/log/LoggingInstrumentationTest.java
  tritium-slf4j/src/main/java/com/palantir/tritium/event/log/LoggingInvocationEventHandler.java
  tritium-slf4j/src/test/java/com/palantir/tritium/event/log/LoggingInvocationEventHandlerTest.java
Labels: merge when ready

#1001 Pin caffeine 2.9.0 for JDK 8 compatibility
  versions.props
Labels: merge when ready, no changelog
