Repository palantir/tritium, pull requests merged in 2021-05, with the labels that each got.

#1083 Tritium provides an annotation processor alternative to dynamic proxies
  .gitattributes
  changelog/@unreleased/pr-1083.v2.yml
  settings.gradle
  tritium-annotations/build.gradle
  tritium-annotations/src/main/java/com/palantir/tritium/annotations/Instrument.java
  tritium-annotations/src/main/java/com/palantir/tritium/annotations/internal/InstrumentationBuilder.java
  tritium-annotations/src/main/java/com/palantir/tritium/annotations/internal/InstrumentedTypeFactory.java
  tritium-core/src/main/java/com/palantir/tritium/event/CompositeInvocationEventHandler.java
  tritium-core/src/main/java/com/palantir/tritium/event/Handlers.java
  tritium-lib/build.gradle
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentation.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentationAdvice.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/InvocationEventProxy.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InvocationEventProxyTest.java
  tritium-processor/build.gradle
  tritium-processor/src/main/java/com/palantir/tritium/processor/MethodElements.java
  tritium-processor/src/main/java/com/palantir/tritium/processor/Methods.java
  tritium-processor/src/main/java/com/palantir/tritium/processor/Parameters.java
  tritium-processor/src/main/java/com/palantir/tritium/processor/TritiumAnnotationProcessor.java
  tritium-processor/src/main/java/com/palantir/tritium/processor/TypeElements.java
  tritium-processor/src/main/java/com/palantir/tritium/processor/TypeNames.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/AnnotatedAbstractClass.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/AnnotatedClass.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/BindsParameter.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/DelegateToCallable.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/DelegateToRunnable.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/DeprecatedInterface.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/DeprecatedMethod.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/Empty.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/HasDefaultMethod.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/HasToString.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/OverlappingNames.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/Overloaded.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/Parameterized.java
  tritium-processor/src/test/java/com/palantir/tritium/examples/Simple.java
  tritium-processor/src/test/java/com/palantir/tritium/processor/DynamicProxyTest.java
  tritium-processor/src/test/java/com/palantir/tritium/processor/TritiumProcessorTest.java
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedBindsParameter.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDelegateToCallable.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDelegateToRunnable.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDeprecatedInterface.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedDeprecatedMethod.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedHasDefaultMethod.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedHasToString.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedOverlappingNames.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedOverloaded.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedParameterized.java.generated
  tritium-processor/src/test/resources/com/palantir/tritium/examples/InstrumentedSimple.java.generated
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1085 Enable gradle incremental annotation processing for tritium-processor
  changelog/@unreleased/pr-1085.v2.yml
  tritium-processor/build.gradle
  tritium-processor/src/main/java/com/palantir/tritium/processor/TritiumAnnotationProcessor.java
  tritium-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
  tritium-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
Labels: autorelease, merge when ready

#1088 JMH gradle plugin 0.6.4
  changelog/@unreleased/pr-1088.v2.yml
  tritium-jmh/build.gradle
Labels: merge when ready

#1089 caffeine 2.9.1
  versions.lock
  versions.props
Labels: merge when ready, no changelog
