Repository palantir/tritium, pull requests merged in 2021-03, with the labels that each got.

#1006 Use SOURCE retention for immutables style annotations
  tritium-caffeine/build.gradle
  tritium-jmh/build.gradle
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/ProxyBenchmark.java
  tritium-lib/build.gradle
  tritium-metrics-jvm/build.gradle
  tritium-metrics/build.gradle
  tritium-registry/build.gradle
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ImmutablesStyle.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/MetricName.java
  tritium-slf4j/build.gradle
  tritium-tracing/build.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#1012 Allow executor queuedDuration metrics to be disabled
  changelog/@unreleased/pr-1012.v2.yml
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/TaggedMetricsExecutorService.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/TaggedMetricsExecutorServiceTest.java
Labels: autorelease, merge when ready

#1017 Apply com.palantir.baseline-fix-gradle-java
  build.gradle
Labels: merge when ready, no changelog

#1021 Don't include performance logging in the Tritium.instrument method
  changelog/@unreleased/pr-1021.v2.yml
  tritium-lib/src/main/java/com/palantir/tritium/Tritium.java
Labels: autorelease, merge when ready
