Repository palantir/tritium, pull requests merged in 2021-06, with the labels that each got.

#1105 Require JDK 11+ for source & bytecode compatibility
  .java-version
  build.gradle
  changelog/@unreleased/pr-1105.v2.yml
  tritium-caffeine/build.gradle
  tritium-lib/src/main/java/com/palantir/tritium/Tritium.java
  tritium-lib/src/main/java/com/palantir/tritium/proxy/Instrumentation.java
  tritium-lib/src/test/java/com/palantir/tritium/TritiumTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/InstrumentedSslEngine.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistriesTest.java
  tritium-proxy/src/main/java/com/palantir/tritium/proxy/Proxies.java
  tritium-proxy/src/test/java/com/palantir/tritium/proxy/ProxiesTest.java
  tritium-slf4j/src/main/java/com/palantir/tritium/event/log/LoggingInvocationEventHandler.java
  tritium-tracing/src/main/java/com/palantir/tritium/tracing/RemotingCompatibleTracingInvocationEventHandler.java
Labels: autorelease, merge when ready

#1106 Consolidate Gradle plugin coordinates in main build.gradle
  build.gradle
  tritium-jmh/build.gradle
Labels: merge when ready, no changelog

#1108 Simplify TritiumAnnotationProcessor annotation selection
  changelog/@unreleased/pr-1108.v2.yml
  tritium-processor/build.gradle
  tritium-processor/src/main/java/com/palantir/tritium/processor/TritiumAnnotationProcessor.java
  versions.lock
Labels: merge when ready

#1109 Add autorelease autolabeler for java changes
  .github/autolabeler.yml
Labels: autorelease, merge when ready, no changelog

#1116 The Instrument annotation uses source retention
  changelog/@unreleased/pr-1116.v2.yml
  tritium-annotations/src/main/java/com/palantir/tritium/annotations/Instrument.java
Labels: autorelease, merge when ready

#1125 Document the Tritium annotation processor
  README.md
Labels: merge when ready, no changelog
