Repository palantir/tritium, pull requests merged in 2022-09, with the labels that each got.

#1567 Rely on gradle-baseline provided error-prone
  build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#1576 Use baseline-null-away
  build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#1577 Normalize versions.props locators
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#1522 Optimize Proxies.interfaces
  tritium-lib/src/main/java/com/palantir/tritium/proxy/ByteBuddyInstrumentation.java
  tritium-proxy/build.gradle
  tritium-proxy/src/main/java/com/palantir/tritium/proxy/Proxies.java
  tritium-proxy/src/test/java/com/palantir/tritium/proxy/ProxiesTest.java
Labels: merge when ready, autorelease, no changelog

#1589 Tritium registry 'getMetrics()' doesn't throw on duplicate names
  changelog/@unreleased/pr-1589.v2.yml
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/AbstractTaggedMetricRegistry.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/TaggedMetricRegistryTest.java
Labels: merge when ready, autorelease
