Repository palantir/tritium, pull requests merged in 2022-03, with the labels that each got.

#1371 Run jqwik tests
  tritium-registry/build.gradle
  versions.lock
Labels: merge when ready, no changelog

#1368 [WIP] Compact MetricName tag map implementation
  changelog/@unreleased/pr-1368.v2.yml
  tritium-jmh/build.gradle
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/NestedMetricsBenchmark.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ExtraEntrySortedMap.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/PrehashedSortedMap.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/RealMetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/TagMap.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/ExtraEntrySortedMapTest.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/TagMapTest.java
Labels: merge when ready, autorelease

#1373 Flatten MetricName builder
  changelog/@unreleased/pr-1373.v2.yml
  tritium-jmh/src/jmh/java/com/palantir/tritium/microbenchmarks/MetricNameBenchmark.java
  tritium-registry/build.gradle
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ImmutableMetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/ImmutablesStyle.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/MetricName.java
  tritium-registry/src/main/java/com/palantir/tritium/metrics/registry/RealMetricName.java
  tritium-registry/src/test/java/com/palantir/tritium/metrics/registry/MetricNameTest.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease

#1376 ignoreGradleMetadata
  build.gradle
  versions.lock
Labels: merge when ready, no changelog

#1393 Clarify total returns null when either heap or non-heap unavailable
  tritium-metrics-jvm/build.gradle
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
Labels: merge when ready

#1392 Memory gauges report null when data is unavailable
  changelog/@unreleased/pr-1392.v2.yml
  tritium-metrics-jvm/build.gradle
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
Labels: merge when ready, autorelease
