Repository palantir/tritium, pull requests merged in 2024-04, with the labels that each got.

#1921 Combine hit and miss cache metrics into single tagged metric
  changelog/@unreleased/pr-1921.v2.yml
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CacheStats.java
  tritium-caffeine/src/main/metrics/cache.yml
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
Labels: merge when ready, autorelease

#1932 Update CacheStats docs
  README.md
Labels: merge when ready, no changelog

#1936 Implement metrics to report the JVM DNS cache TTL values
  changelog/@unreleased/pr-1936.v2.yml
  tritium-metrics-jvm/src/main/java/com/palantir/tritium/metrics/jvm/JvmMetrics.java
  tritium-metrics-jvm/src/main/metrics/metrics.yml
  tritium-metrics-jvm/src/test/java/com/palantir/tritium/metrics/jvm/JvmMetricsTest.java
  versions.lock
  versions.props
Labels: merge when ready, autorelease, 🤖 fix nits
