Repository palantir/tritium, pull requests merged in 2024-03, with the labels that each got.

#1868 Use SystemStubsExtension for system property unit tests
  tritium-core/build.gradle
  tritium-core/src/test/java/com/palantir/tritium/event/AbstractInvocationEventHandlerTest.java
  tritium-core/src/test/java/com/palantir/tritium/event/InstrumentationPropertiesTest.java
  tritium-lib/build.gradle
  tritium-lib/src/test/java/com/palantir/tritium/TritiumTest.java
  tritium-lib/src/test/java/com/palantir/tritium/event/log/LoggingInstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/InstrumentationTest.java
  tritium-lib/src/test/java/com/palantir/tritium/proxy/subpackage/ByteBuddyInstrumentationPackageAccessTest.java
  tritium-metrics/build.gradle
  tritium-metrics/src/test/java/com/palantir/tritium/event/metrics/MetricsBooleanSupplierTest.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/InstrumentedSslContextTest.java
  tritium-slf4j/build.gradle
  tritium-slf4j/src/test/java/com/palantir/tritium/event/log/LoggingInvocationEventHandlerTest.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog, 🤖 fix nits

#1897 Initial Caffeine CacheStats recorder
  README.md
  changelog/@unreleased/pr-1897.v2.yml
  tritium-caffeine/build.gradle
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CacheStats.java
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStats.java
  tritium-caffeine/src/main/metrics/cache-metrics.yml
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
  tritium-metrics/src/main/java/com/palantir/tritium/metrics/MetricRegistries.java
  tritium-metrics/src/test/java/com/palantir/tritium/metrics/MetricRegistriesTest.java
Labels: merge when ready, autorelease

#1917 Fix ErrorProne configuration
  build.gradle
Labels: merge when ready, no changelog

#1919 Add cache size metrics to CacheStats
  changelog/@unreleased/pr-1919.v2.yml
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CacheStats.java
  tritium-caffeine/src/main/metrics/cache-metrics.yml
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
Labels: merge when ready, autorelease

#1920 Change CacheState.register to a fluent API
  changelog/@unreleased/pr-1920.v2.yml
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CacheStats.java
  tritium-caffeine/src/main/metrics/cache-metrics.yml
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
Labels: merge when ready, autorelease

#1922 Check that stats recording is enabled when registering a cache
  tritium-caffeine/build.gradle
  tritium-caffeine/src/main/java/com/palantir/tritium/metrics/caffeine/CacheStats.java
  tritium-caffeine/src/test/java/com/palantir/tritium/metrics/caffeine/CaffeineCacheStatsTest.java
  versions.lock
Labels: merge when ready, autorelease, no changelog, 🤖 fix nits
